# Generated by Django 5.0.4 on 2024-05-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('mfg_date', models.CharField(max_length=30)),
                ('exp_date', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('product_pic', models.FileField(upload_to='')),
            ],
        ),
    ]
